
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 27 02:54:50 PDT 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_decremento = 52;
  public static final int Llave_c = 57;
  public static final int Op_booleano = 53;
  public static final int Llave_a = 56;
  public static final int Ttexto = 7;
  public static final int Diferente = 43;
  public static final int Procedimientos = 18;
  public static final int Tsimbolo = 6;
  public static final int Op_atribucion_suma = 46;
  public static final int Variable = 15;
  public static final int Funciones = 17;
  public static final int Corchete_c = 59;
  public static final int Corchete_a = 58;
  public static final int Para = 26;
  public static final int Op_logico_or = 36;
  public static final int Op_bitwise_or = 39;
  public static final int Division = 34;
  public static final int Cadena = 61;
  public static final int Parentesis_c = 55;
  public static final int Op_bitwise_and = 38;
  public static final int Parentesis_a = 54;
  public static final int Fin = 23;
  public static final int Tfecha = 10;
  public static final int P_coma = 60;
  public static final int EOF = 0;
  public static final int MayorQue = 40;
  public static final int error = 1;
  public static final int Tdecimal = 5;
  public static final int Funcion = 19;
  public static final int Op_atribucion_modulo = 50;
  public static final int Romper = 28;
  public static final int Linea = 2;
  public static final int Imprimir = 29;
  public static final int Devolver = 20;
  public static final int Thora = 11;
  public static final int ERROR = 64;
  public static final int Op_atribucion_resta = 47;
  public static final int TLogico = 8;
  public static final int MenorIgual = 45;
  public static final int Variables = 14;
  public static final int Op_atribucion_division = 49;
  public static final int Tcurp = 13;
  public static final int Op_logico_not = 37;
  public static final int Op_logico_and = 35;
  public static final int Tfechahora = 9;
  public static final int Inicio = 22;
  public static final int Identificador = 62;
  public static final int Op_atribucion_multiplicacion = 48;
  public static final int Tentero = 4;
  public static final int Si = 24;
  public static final int Resta = 32;
  public static final int MenorQue = 41;
  public static final int MayorIgual = 44;
  public static final int Sino = 25;
  public static final int Igualdad = 42;
  public static final int Mientras = 27;
  public static final int Procedimiento = 21;
  public static final int Multiplicacion = 33;
  public static final int Op_incremento = 51;
  public static final int Numero = 63;
  public static final int CodigoPrincipal = 16;
  public static final int Suma = 31;
  public static final int Trfc = 12;
  public static final int Igual = 30;
  public static final int Comillas = 3;
  public static final int Entonces = 56;
}

