
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 26 13:17:08 PDT 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 28;
  public static final int Llave_c = 35;
  public static final int Op_booleano = 31;
  public static final int Llave_a = 34;
  public static final int T_dato = 4;
  public static final int Procedimientos = 10;
  public static final int Variable = 7;
  public static final int Funciones = 9;
  public static final int Corchete_c = 37;
  public static final int Corchete_a = 36;
  public static final int Para = 18;
  public static final int Division = 26;
  public static final int Int = 5;
  public static final int Cadena = 39;
  public static final int Parentesis_c = 33;
  public static final int Fin = 15;
  public static final int Parentesis_a = 32;
  public static final int P_coma = 38;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Funcion = 11;
  public static final int Romper = 20;
  public static final int Linea = 2;
  public static final int Imprimir = 21;
  public static final int Devolver = 12;
  public static final int Op_atribucion = 29;
  public static final int ERROR = 42;
  public static final int Op_logico = 27;
  public static final int Variables = 6;
  public static final int Inicio = 14;
  public static final int Identificador = 40;
  public static final int Si = 16;
  public static final int Resta = 24;
  public static final int Sino = 17;
  public static final int Mientras = 19;
  public static final int Procedimiento = 13;
  public static final int Multiplicacion = 25;
  public static final int Op_incremento = 30;
  public static final int Numero = 41;
  public static final int CodigoPrincipal = 8;
  public static final int Suma = 23;
  public static final int Igual = 22;
  public static final int Comillas = 3;
}

