
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 28 01:36:55 PDT 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Llave_c = 55;
  public static final int Llave_a = 54;
  public static final int Ttexto = 7;
  public static final int Diferente = 44;
  public static final int Procedimientos = 18;
  public static final int Tsimbolo = 6;
  public static final int Op_atribucion_suma = 47;
  public static final int Variable = 15;
  public static final int Funciones = 17;
  public static final int Corchete_c = 57;
  public static final int Corchete_a = 56;
  public static final int Para = 27;
  public static final int Op_logico_or = 37;
  public static final int Op_bitwise_or = 40;
  public static final int Division = 35;
  public static final int Cadena = 59;
  public static final int Parentesis_c = 53;
  public static final int Op_bitwise_and = 39;
  public static final int Parentesis_a = 52;
  public static final int Fin = 23;
  public static final int Tfecha = 10;
  public static final int P_coma = 58;
  public static final int EOF = 0;
  public static final int MayorQue = 41;
  public static final int error = 1;
  public static final int Tdecimal = 5;
  public static final int Funcion = 19;
  public static final int Op_atribucion_modulo = 51;
  public static final int Romper = 29;
  public static final int Linea = 2;
  public static final int Imprimir = 30;
  public static final int Devolver = 20;
  public static final int Thora = 11;
  public static final int ERROR = 62;
  public static final int Op_atribucion_resta = 48;
  public static final int TLogico = 8;
  public static final int MenorIgual = 46;
  public static final int Entonces = 25;
  public static final int Variables = 14;
  public static final int Op_atribucion_division = 50;
  public static final int Tcurp = 13;
  public static final int Op_logico_not = 38;
  public static final int Op_logico_and = 36;
  public static final int Tfechahora = 9;
  public static final int Inicio = 22;
  public static final int Identificador = 60;
  public static final int Op_atribucion_multiplicacion = 49;
  public static final int Tentero = 4;
  public static final int Si = 24;
  public static final int Resta = 33;
  public static final int MenorQue = 42;
  public static final int MayorIgual = 45;
  public static final int Sino = 26;
  public static final int Igualdad = 43;
  public static final int Mientras = 28;
  public static final int Procedimiento = 21;
  public static final int Multiplicacion = 34;
  public static final int Numero = 61;
  public static final int CodigoPrincipal = 16;
  public static final int Suma = 32;
  public static final int Trfc = 12;
  public static final int Igual = 31;
  public static final int Comillas = 3;
}

