/* The following code was generated by JFlex 1.4.3 on 28/05/23, 22:44 */

package codigo;
import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 28/05/23, 22:44 from the specification file
 * <tt>C:/Users/andre/OneDrive/Documents/NetBeansProjects/AnalizadorLexicoSintactico/src/codigo/LexerCup.flex</tt>
 */
class LexerCup implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  5,  0,  0,  3,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     3, 43,  6,  4,  0, 46, 41,  0, 47, 48, 40, 39,  3, 28,  0, 36, 
    32, 33, 34, 35, 37, 37,  2,  2,  2,  2, 15, 53, 45, 38, 44,  0, 
     0, 29, 31, 31, 31, 29, 31, 31, 30, 29, 31, 31, 31, 30, 31, 29, 
    31, 31, 31, 31, 31, 29, 31, 31, 31, 31, 31, 51,  0, 52,  0,  1, 
     0,  8, 11, 20, 19, 13, 24, 23, 25, 10,  1,  1, 12, 21, 16, 18, 
    27,  1,  9, 14, 17, 26,  7,  1, 22,  1,  1, 49, 42, 50,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\4\1\5\15\2\1\6"+
    "\1\2\4\3\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\1\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\3\3\0\1\27\7\2\1\30"+
    "\14\2\1\31\1\2\1\0\2\3\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\7\0"+
    "\2\2\1\44\25\2\3\0\2\45\7\2\1\46\5\2"+
    "\1\47\1\2\2\50\4\2\1\51\1\52\2\2\1\3"+
    "\3\0\10\2\1\53\4\2\1\54\1\2\1\55\1\56"+
    "\2\2\3\0\1\2\1\57\2\2\1\60\1\61\12\2"+
    "\1\0\2\45\1\2\2\62\2\2\1\63\1\2\1\64"+
    "\1\0\2\2\1\65\2\2\1\66\1\67\1\70\1\71"+
    "\1\72\1\0\1\73\4\2\1\0\1\2\1\0\1\74"+
    "\3\2\3\0\1\75\1\0\1\76\2\2\2\0\3\2"+
    "\2\0\3\2\1\77\1\0\1\100\2\101\2\0\2\2"+
    "\2\0\1\102\1\2\1\77\1\0\1\2\1\103\1\2"+
    "\1\104";

  private static int [] zzUnpackAction() {
    int [] result = new int[258];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\330\0\u010e\0\u0144\0\u017a"+
    "\0\u01b0\0\u01e6\0\u021c\0\u0252\0\u0288\0\u02be\0\u02f4\0\u032a"+
    "\0\u0360\0\u0396\0\u03cc\0\u0402\0\u0438\0\u046e\0\u04a4\0\u04da"+
    "\0\u0510\0\u0546\0\u057c\0\u05b2\0\u05e8\0\u061e\0\u0654\0\u068a"+
    "\0\u06c0\0\u06f6\0\u072c\0\u0762\0\u0798\0\66\0\66\0\66"+
    "\0\66\0\66\0\66\0\u07ce\0\u0804\0\u083a\0\u0144\0\u0144"+
    "\0\u0870\0\u08a6\0\u08dc\0\u0912\0\u0948\0\u097e\0\u09b4\0\u09ea"+
    "\0\u0a20\0\u0a56\0\u0a8c\0\u0ac2\0\u0af8\0\u0b2e\0\u0b64\0\u0b9a"+
    "\0\u0bd0\0\u0c06\0\u0c3c\0\u0c72\0\66\0\u0ca8\0\u0cde\0\u0d14"+
    "\0\u0d4a\0\66\0\66\0\66\0\66\0\66\0\66\0\66"+
    "\0\66\0\66\0\66\0\u0d80\0\u0db6\0\u0dec\0\u0e22\0\u0e58"+
    "\0\u0e8e\0\u0ec4\0\u0efa\0\u0f30\0\154\0\u0f66\0\u0f9c\0\u0fd2"+
    "\0\u1008\0\u103e\0\u1074\0\u10aa\0\u10e0\0\u1116\0\u114c\0\u1182"+
    "\0\u11b8\0\u11ee\0\u1224\0\u125a\0\u1290\0\u12c6\0\u12fc\0\u1332"+
    "\0\u1368\0\u139e\0\u13d4\0\u140a\0\u1440\0\u1476\0\u14ac\0\u14e2"+
    "\0\u1518\0\u154e\0\u1584\0\u15ba\0\u15f0\0\u1626\0\154\0\u165c"+
    "\0\u1692\0\u16c8\0\u16fe\0\u1734\0\154\0\u176a\0\66\0\154"+
    "\0\u17a0\0\u17d6\0\u180c\0\u1842\0\154\0\154\0\u1878\0\u18ae"+
    "\0\66\0\u18e4\0\u191a\0\u1950\0\u1986\0\u19bc\0\u19f2\0\u1a28"+
    "\0\u1a5e\0\u1a94\0\u1aca\0\u1b00\0\154\0\u1b36\0\u1b6c\0\u1ba2"+
    "\0\u1bd8\0\u1c0e\0\u1c44\0\154\0\154\0\u1c7a\0\u1cb0\0\u1ce6"+
    "\0\u1d1c\0\u1d52\0\u1d88\0\154\0\u1dbe\0\u1df4\0\154\0\154"+
    "\0\u1e2a\0\u1e60\0\u1e96\0\u1ecc\0\u1f02\0\u1f38\0\u1f6e\0\u1fa4"+
    "\0\u1fda\0\u2010\0\u2046\0\u1ce6\0\66\0\u207c\0\66\0\154"+
    "\0\u20b2\0\u20e8\0\154\0\u211e\0\154\0\u2154\0\u218a\0\u21c0"+
    "\0\u21f6\0\u222c\0\u2262\0\u2298\0\u22ce\0\154\0\154\0\154"+
    "\0\u2304\0\154\0\u233a\0\u2370\0\u23a6\0\u23dc\0\u2412\0\u2448"+
    "\0\u247e\0\154\0\u24b4\0\u24ea\0\u2520\0\u2556\0\u258c\0\u25c2"+
    "\0\66\0\u25f8\0\66\0\u262e\0\u2664\0\u269a\0\u26d0\0\u2706"+
    "\0\u273c\0\u2772\0\u27a8\0\u27de\0\u2814\0\u284a\0\u2880\0\u28b6"+
    "\0\u28ec\0\u2922\0\154\0\u2958\0\u298e\0\u29c4\0\u29fa\0\u2a30"+
    "\0\u2a66\0\u2a9c\0\66\0\u2ad2\0\66\0\u2b08\0\u2b3e\0\66"+
    "\0\u2b74\0\154";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[258];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\5\1\7\1\10"+
    "\1\3\1\11\1\12\1\3\1\13\1\14\1\15\1\2"+
    "\1\3\1\16\1\3\1\17\1\20\1\21\2\3\1\22"+
    "\1\23\1\3\1\24\1\25\3\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\4\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\67\0\2\3\4\0\10\3\1\0"+
    "\14\3\1\0\7\3\1\0\1\3\22\0\1\54\14\0"+
    "\1\55\14\0\1\56\3\0\4\54\1\56\1\54\23\0"+
    "\1\5\1\0\1\5\60\0\5\6\1\0\60\6\5\57"+
    "\1\0\1\60\57\57\1\0\2\3\4\0\1\3\1\61"+
    "\6\3\1\0\14\3\1\0\7\3\1\0\1\3\21\0"+
    "\2\3\4\0\10\3\1\0\2\3\1\62\5\3\1\63"+
    "\3\3\1\0\7\3\1\0\1\3\21\0\2\3\4\0"+
    "\10\3\1\0\1\64\4\3\1\65\6\3\1\0\7\3"+
    "\1\0\1\3\21\0\2\3\4\0\10\3\1\0\2\3"+
    "\1\66\11\3\1\0\7\3\1\0\1\3\21\0\2\3"+
    "\4\0\10\3\1\0\1\67\13\3\1\0\7\3\1\0"+
    "\1\3\21\0\2\3\4\0\3\3\1\70\4\3\1\0"+
    "\14\3\1\0\7\3\1\0\1\3\21\0\2\3\4\0"+
    "\6\3\1\71\1\3\1\0\14\3\1\0\7\3\1\0"+
    "\1\3\21\0\2\3\4\0\6\3\1\72\1\3\1\0"+
    "\14\3\1\0\7\3\1\0\1\3\21\0\2\3\4\0"+
    "\10\3\1\0\2\3\1\73\7\3\1\74\1\3\1\0"+
    "\7\3\1\0\1\3\21\0\2\3\4\0\3\3\1\75"+
    "\4\3\1\0\14\3\1\0\7\3\1\0\1\3\21\0"+
    "\2\3\4\0\3\3\1\76\2\3\1\77\1\3\1\0"+
    "\12\3\1\100\1\3\1\0\7\3\1\0\1\3\21\0"+
    "\2\3\4\0\1\3\1\101\6\3\1\0\2\3\1\102"+
    "\11\3\1\0\7\3\1\0\1\3\21\0\2\3\4\0"+
    "\1\3\1\103\1\104\5\3\1\0\14\3\1\0\7\3"+
    "\1\0\1\3\66\0\1\105\20\0\2\3\4\0\10\3"+
    "\1\0\14\3\1\0\3\106\4\3\1\0\1\3\22\0"+
    "\1\4\14\0\1\107\20\0\1\110\3\4\1\0\1\4"+
    "\22\0\1\4\14\0\1\55\14\0\1\56\3\0\4\4"+
    "\1\56\1\4\22\0\1\111\14\0\1\55\14\0\1\56"+
    "\3\0\4\4\1\56\1\111\22\0\1\54\14\0\1\55"+
    "\14\0\1\56\3\0\2\111\2\54\1\56\1\54\66\0"+
    "\1\112\65\0\1\113\65\0\1\114\65\0\1\115\70\0"+
    "\1\116\66\0\1\117\61\0\1\120\65\0\1\121\65\0"+
    "\1\122\65\0\1\123\53\0\1\124\33\0\1\54\35\0"+
    "\4\54\1\0\1\54\22\0\1\125\35\0\1\126\1\127"+
    "\2\130\1\0\1\130\22\0\1\125\35\0\1\131\1\132"+
    "\2\125\1\0\1\125\21\0\2\3\4\0\2\3\1\133"+
    "\5\3\1\0\14\3\1\0\7\3\1\0\1\3\21\0"+
    "\2\3\4\0\10\3\1\0\5\3\1\134\6\3\1\0"+
    "\7\3\1\0\1\3\21\0\2\3\4\0\10\3\1\0"+
    "\4\3\1\135\7\3\1\0\7\3\1\0\1\3\21\0"+
    "\2\3\4\0\3\3\1\136\4\3\1\0\14\3\1\0"+
    "\7\3\1\0\1\3\21\0\2\3\4\0\10\3\1\0"+
    "\13\3\1\137\1\0\7\3\1\0\1\3\21\0\2\3"+
    "\4\0\10\3\1\0\7\3\1\140\4\3\1\0\7\3"+
    "\1\0\1\3\21\0\2\3\4\0\10\3\1\0\1\3"+
    "\1\141\12\3\1\0\7\3\1\0\1\3\21\0\2\3"+
    "\4\0\10\3\1\0\1\142\4\3\1\143\6\3\1\0"+
    "\7\3\1\0\1\3\21\0\2\3\4\0\10\3\1\0"+
    "\6\3\1\144\5\3\1\0\7\3\1\0\1\3\21\0"+
    "\2\3\4\0\1\145\7\3\1\0\4\3\1\146\7\3"+
    "\1\0\7\3\1\0\1\3\21\0\2\3\4\0\10\3"+
    "\1\0\3\3\1\147\10\3\1\0\7\3\1\0\1\3"+
    "\21\0\2\3\4\0\2\3\1\150\5\3\1\0\14\3"+
    "\1\0\7\3\1\0\1\3\21\0\2\3\4\0\6\3"+
    "\1\151\1\3\1\0\14\3\1\0\7\3\1\0\1\3"+
    "\21\0\2\3\4\0\10\3\1\0\1\152\13\3\1\0"+
    "\7\3\1\0\1\3\21\0\2\3\4\0\10\3\1\0"+
    "\4\3\1\153\7\3\1\0\7\3\1\0\1\3\21\0"+
    "\2\3\4\0\10\3\1\0\1\154\13\3\1\0\7\3"+
    "\1\0\1\3\21\0\2\3\4\0\7\3\1\155\1\0"+
    "\4\3\1\156\7\3\1\0\7\3\1\0\1\3\21\0"+
    "\2\3\4\0\2\3\1\157\5\3\1\0\14\3\1\0"+
    "\7\3\1\0\1\3\21\0\2\3\4\0\2\3\1\160"+
    "\5\3\1\0\14\3\1\0\7\3\1\0\1\3\21\0"+
    "\2\3\4\0\10\3\1\0\2\3\1\161\11\3\1\0"+
    "\7\3\1\0\1\3\21\0\2\3\4\0\10\3\1\0"+
    "\14\3\1\0\3\162\4\3\1\0\1\3\60\0\4\163"+
    "\1\0\1\163\22\0\1\54\14\0\1\107\20\0\4\54"+
    "\1\0\1\54\22\0\1\54\14\0\1\56\14\0\1\56"+
    "\3\0\4\54\1\56\1\54\22\0\1\164\35\0\4\164"+
    "\1\0\1\164\37\0\1\165\14\0\1\165\7\0\1\165"+
    "\23\0\1\166\35\0\1\167\3\166\1\0\1\166\22\0"+
    "\1\167\14\0\1\165\14\0\1\165\3\0\3\166\1\167"+
    "\1\165\1\167\22\0\1\167\14\0\1\165\14\0\1\165"+
    "\3\0\4\167\1\165\1\167\22\0\1\125\36\0\3\125"+
    "\1\0\1\125\37\0\1\165\14\0\1\165\3\0\3\125"+
    "\1\0\1\165\22\0\2\3\4\0\3\3\1\170\4\3"+
    "\1\0\14\3\1\0\7\3\1\0\1\3\21\0\2\3"+
    "\4\0\10\3\1\0\13\3\1\171\1\0\7\3\1\0"+
    "\1\3\21\0\2\3\4\0\10\3\1\0\4\3\1\172"+
    "\7\3\1\0\7\3\1\0\1\3\21\0\2\3\4\0"+
    "\2\3\1\173\5\3\1\0\14\3\1\0\7\3\1\0"+
    "\1\3\21\0\2\3\4\0\3\3\1\174\4\3\1\0"+
    "\14\3\1\0\7\3\1\0\1\3\21\0\2\3\4\0"+
    "\6\3\1\175\1\3\1\0\2\3\1\176\11\3\1\0"+
    "\7\3\1\0\1\3\21\0\2\3\4\0\10\3\1\0"+
    "\2\3\1\177\11\3\1\0\7\3\1\0\1\3\21\0"+
    "\2\3\4\0\4\3\1\200\3\3\1\0\14\3\1\0"+
    "\7\3\1\0\1\3\21\0\2\3\4\0\10\3\1\0"+
    "\1\3\1\201\12\3\1\0\7\3\1\0\1\3\21\0"+
    "\2\3\4\0\10\3\1\0\2\3\1\202\11\3\1\0"+
    "\7\3\1\0\1\3\21\0\2\3\4\0\3\3\1\203"+
    "\4\3\1\0\14\3\1\0\7\3\1\0\1\3\21\0"+
    "\2\3\4\0\3\3\1\204\4\3\1\0\14\3\1\0"+
    "\7\3\1\0\1\3\21\0\2\3\4\0\10\3\1\0"+
    "\13\3\1\205\1\0\7\3\1\0\1\3\21\0\2\3"+
    "\4\0\10\3\1\0\1\206\13\3\1\0\7\3\1\0"+
    "\1\3\20\0\1\207\2\210\2\207\1\0\1\207\10\210"+
    "\1\207\14\210\1\207\7\210\1\207\1\210\20\207\1\0"+
    "\2\3\4\0\10\3\1\0\11\3\1\211\2\3\1\0"+
    "\7\3\1\0\1\3\21\0\2\3\4\0\10\3\1\0"+
    "\4\3\1\212\7\3\1\0\7\3\1\0\1\3\21\0"+
    "\2\3\4\0\10\3\1\0\1\3\1\213\12\3\1\0"+
    "\7\3\1\0\1\3\21\0\2\3\4\0\6\3\1\214"+
    "\1\3\1\0\14\3\1\0\7\3\1\0\1\3\21\0"+
    "\2\3\4\0\1\3\1\215\6\3\1\0\14\3\1\0"+
    "\7\3\1\0\1\3\21\0\2\3\4\0\1\3\1\216"+
    "\6\3\1\0\14\3\1\0\7\3\1\0\1\3\21\0"+
    "\2\3\4\0\10\3\1\0\4\3\1\217\7\3\1\0"+
    "\7\3\1\0\1\3\21\0\2\3\4\0\10\3\1\0"+
    "\14\3\1\0\3\220\4\3\1\0\1\3\22\0\1\167"+
    "\35\0\4\167\1\0\1\167\22\0\1\164\35\0\4\164"+
    "\1\0\1\164\12\0\1\221\7\0\1\222\35\0\4\222"+
    "\1\0\1\222\37\0\1\223\14\0\1\165\7\0\1\165"+
    "\40\0\1\224\47\0\2\3\4\0\1\3\1\225\6\3"+
    "\1\0\14\3\1\0\7\3\1\0\1\3\21\0\2\3"+
    "\4\0\6\3\1\226\1\3\1\0\14\3\1\0\7\3"+
    "\1\0\1\3\21\0\2\3\4\0\3\3\1\227\4\3"+
    "\1\0\14\3\1\0\7\3\1\0\1\3\21\0\2\3"+
    "\4\0\3\3\1\230\4\3\1\0\14\3\1\0\7\3"+
    "\1\0\1\3\21\0\2\3\4\0\10\3\1\0\4\3"+
    "\1\231\7\3\1\0\7\3\1\0\1\3\21\0\2\3"+
    "\4\0\2\3\1\232\5\3\1\0\14\3\1\0\7\3"+
    "\1\0\1\3\21\0\2\3\4\0\10\3\1\0\1\233"+
    "\13\3\1\0\7\3\1\0\1\3\21\0\2\3\4\0"+
    "\10\3\1\0\2\3\1\234\11\3\1\0\7\3\1\0"+
    "\1\3\21\0\2\3\4\0\10\3\1\0\2\3\1\235"+
    "\11\3\1\0\7\3\1\0\1\3\21\0\2\3\4\0"+
    "\5\3\1\236\2\3\1\0\14\3\1\0\7\3\1\0"+
    "\1\3\21\0\2\3\4\0\10\3\1\0\5\3\1\237"+
    "\6\3\1\0\7\3\1\0\1\3\21\0\2\3\4\0"+
    "\10\3\1\0\7\3\1\240\4\3\1\0\7\3\1\0"+
    "\1\3\21\0\2\3\4\0\10\3\1\0\1\3\1\241"+
    "\12\3\1\0\7\3\1\0\1\3\21\0\2\3\4\0"+
    "\1\3\1\242\6\3\1\0\14\3\1\0\7\3\1\0"+
    "\1\3\21\0\2\3\4\0\3\3\1\243\4\3\1\0"+
    "\14\3\1\0\7\3\1\0\1\3\21\0\2\3\4\0"+
    "\1\3\1\244\6\3\1\0\14\3\1\0\7\3\1\0"+
    "\1\3\21\0\2\3\4\0\2\3\1\245\5\3\1\0"+
    "\14\3\1\0\7\3\1\0\1\3\21\0\2\3\4\0"+
    "\6\3\1\246\1\3\1\0\14\3\1\0\7\3\1\0"+
    "\1\3\21\0\1\3\1\247\4\0\10\3\1\0\14\3"+
    "\1\0\3\3\4\247\1\0\1\247\22\0\1\250\35\0"+
    "\4\250\1\0\1\250\22\0\1\222\35\0\4\251\1\0"+
    "\1\251\60\0\4\252\1\0\1\252\21\0\2\3\4\0"+
    "\4\3\1\253\3\3\1\0\14\3\1\0\7\3\1\0"+
    "\1\3\21\0\2\3\4\0\2\3\1\254\5\3\1\0"+
    "\14\3\1\0\7\3\1\0\1\3\21\0\2\3\4\0"+
    "\10\3\1\0\2\3\1\255\11\3\1\0\7\3\1\0"+
    "\1\3\21\0\2\3\4\0\10\3\1\0\5\3\1\256"+
    "\6\3\1\0\7\3\1\0\1\3\21\0\2\3\4\0"+
    "\10\3\1\0\2\3\1\257\11\3\1\0\7\3\1\0"+
    "\1\3\21\0\2\3\4\0\10\3\1\0\2\3\1\260"+
    "\11\3\1\0\7\3\1\0\1\3\21\0\2\3\4\0"+
    "\10\3\1\0\4\3\1\261\7\3\1\0\7\3\1\0"+
    "\1\3\21\0\2\3\4\0\5\3\1\262\2\3\1\0"+
    "\14\3\1\0\7\3\1\0\1\3\21\0\2\3\4\0"+
    "\1\263\7\3\1\0\14\3\1\0\7\3\1\0\1\3"+
    "\21\0\2\3\4\0\1\3\1\264\6\3\1\0\14\3"+
    "\1\0\7\3\1\0\1\3\21\0\2\3\4\0\10\3"+
    "\1\0\2\3\1\265\11\3\1\0\7\3\1\0\1\3"+
    "\21\0\2\3\4\0\2\3\1\266\5\3\1\0\14\3"+
    "\1\0\7\3\1\0\1\3\21\0\2\3\4\0\10\3"+
    "\1\0\11\3\1\267\2\3\1\0\7\3\1\0\1\3"+
    "\21\0\2\3\4\0\10\3\1\0\2\3\1\270\11\3"+
    "\1\0\7\3\1\0\1\3\21\0\2\3\4\0\10\3"+
    "\1\0\3\3\1\271\10\3\1\0\7\3\1\0\1\3"+
    "\21\0\1\3\1\272\4\0\10\3\1\0\14\3\1\0"+
    "\3\3\4\272\1\0\1\272\22\0\1\273\35\0\4\273"+
    "\1\0\1\273\22\0\1\274\35\0\4\274\1\0\1\274"+
    "\22\0\1\275\35\0\4\275\1\0\1\275\21\0\2\3"+
    "\4\0\5\3\1\276\2\3\1\0\14\3\1\0\7\3"+
    "\1\0\1\3\20\0\1\277\2\300\2\277\1\0\1\277"+
    "\10\300\1\277\14\300\1\277\7\300\1\277\1\300\20\277"+
    "\1\0\2\3\4\0\3\3\1\301\4\3\1\0\14\3"+
    "\1\0\7\3\1\0\1\3\21\0\2\3\4\0\6\3"+
    "\1\302\1\3\1\0\14\3\1\0\7\3\1\0\1\3"+
    "\21\0\2\3\4\0\10\3\1\0\2\3\1\303\11\3"+
    "\1\0\7\3\1\0\1\3\21\0\2\3\4\0\6\3"+
    "\1\304\1\3\1\0\14\3\1\0\7\3\1\0\1\3"+
    "\21\0\2\3\4\0\5\3\1\305\2\3\1\0\14\3"+
    "\1\0\7\3\1\0\1\3\21\0\2\3\4\0\10\3"+
    "\1\0\14\3\1\306\7\3\1\0\1\3\21\0\2\3"+
    "\4\0\1\3\1\307\6\3\1\0\14\3\1\0\7\3"+
    "\1\0\1\3\21\0\2\3\4\0\10\3\1\0\2\3"+
    "\1\310\11\3\1\0\7\3\1\0\1\3\21\0\2\3"+
    "\4\0\10\3\1\0\1\311\13\3\1\0\7\3\1\0"+
    "\1\3\21\0\2\3\4\0\3\3\1\312\4\3\1\0"+
    "\14\3\1\0\7\3\1\0\1\3\21\0\1\3\1\313"+
    "\4\0\10\3\1\0\14\3\1\0\3\3\4\313\1\0"+
    "\1\313\22\0\1\314\35\0\4\314\1\0\1\314\21\0"+
    "\2\3\4\0\6\3\1\315\1\3\1\0\14\3\1\0"+
    "\7\3\1\0\1\3\21\0\2\3\4\0\2\3\1\316"+
    "\5\3\1\0\14\3\1\0\7\3\1\0\1\3\21\0"+
    "\2\3\4\0\7\3\1\317\1\0\14\3\1\0\7\3"+
    "\1\0\1\3\21\0\2\3\4\0\2\3\1\320\5\3"+
    "\1\0\14\3\1\0\7\3\1\0\1\3\53\0\1\321"+
    "\33\0\2\3\4\0\7\3\1\322\1\0\14\3\1\0"+
    "\7\3\1\0\1\3\21\0\2\3\4\0\2\3\1\323"+
    "\5\3\1\0\14\3\1\0\7\3\1\0\1\3\21\0"+
    "\2\3\4\0\6\3\1\324\1\3\1\0\14\3\1\0"+
    "\7\3\1\0\1\3\21\0\2\3\4\0\10\3\1\0"+
    "\5\3\1\325\6\3\1\0\7\3\1\0\1\3\21\0"+
    "\1\3\1\326\4\0\10\3\1\0\14\3\1\0\3\3"+
    "\4\326\1\0\1\326\54\0\1\327\32\0\2\3\4\0"+
    "\7\3\1\330\1\0\14\3\1\0\7\3\1\0\1\3"+
    "\31\0\1\331\55\0\2\3\4\0\1\3\1\332\6\3"+
    "\1\0\14\3\1\0\7\3\1\0\1\3\21\0\2\3"+
    "\4\0\7\3\1\333\1\0\14\3\1\0\7\3\1\0"+
    "\1\3\21\0\2\3\4\0\3\3\1\334\4\3\1\0"+
    "\14\3\1\0\7\3\1\0\1\3\21\0\1\3\1\335"+
    "\4\0\10\3\1\0\14\3\1\0\3\3\4\335\1\0"+
    "\1\335\22\0\1\336\35\0\2\337\1\340\1\336\1\0"+
    "\1\336\21\0\2\3\4\0\10\3\1\341\14\3\1\0"+
    "\7\3\1\0\1\3\32\0\1\342\54\0\2\3\4\0"+
    "\10\3\1\343\14\3\1\0\7\3\1\0\1\3\21\0"+
    "\2\3\4\0\6\3\1\344\1\3\1\0\14\3\1\0"+
    "\7\3\1\0\1\3\21\0\1\3\1\345\4\0\10\3"+
    "\1\0\14\3\1\0\3\3\4\345\1\0\1\345\37\0"+
    "\1\346\50\0\1\336\14\0\1\346\20\0\4\336\1\0"+
    "\1\336\37\0\1\346\20\0\4\336\42\0\1\347\46\0"+
    "\2\3\4\0\10\3\1\0\1\350\13\3\1\0\7\3"+
    "\1\0\1\3\21\0\1\3\1\351\4\0\10\3\1\0"+
    "\14\3\1\0\1\351\1\352\5\351\1\0\1\351\60\0"+
    "\4\353\1\0\1\353\44\0\1\354\42\0\2\3\4\0"+
    "\10\3\1\0\1\3\1\355\12\3\1\0\7\3\1\0"+
    "\1\3\21\0\1\3\1\356\4\0\10\3\1\0\14\3"+
    "\1\0\7\356\1\0\1\356\21\0\1\3\1\356\4\0"+
    "\10\3\1\0\14\3\1\0\3\357\4\356\1\0\1\356"+
    "\22\0\1\360\35\0\4\360\1\0\1\360\32\0\1\361"+
    "\54\0\2\3\4\0\10\3\1\0\2\3\1\362\11\3"+
    "\1\0\7\3\1\0\1\3\21\0\1\3\1\363\4\0"+
    "\10\3\1\0\14\3\1\0\7\363\1\0\1\363\21\0"+
    "\1\3\1\363\4\0\10\3\1\0\14\3\1\0\3\364"+
    "\4\363\1\0\1\363\37\0\1\365\101\0\1\366\33\0"+
    "\2\3\4\0\7\3\1\367\1\0\14\3\1\0\7\3"+
    "\1\0\1\3\21\0\2\3\4\0\10\3\1\0\14\3"+
    "\1\0\1\3\2\370\4\3\1\0\1\3\60\0\4\371"+
    "\1\0\1\371\30\0\1\372\56\0\2\3\4\0\10\3"+
    "\1\373\14\3\1\0\7\3\1\0\1\3\21\0\2\3"+
    "\4\0\10\3\1\0\14\3\1\0\1\3\2\374\4\3"+
    "\1\0\1\3\22\0\1\375\35\0\4\375\1\0\1\375"+
    "\34\0\1\376\52\0\2\3\4\0\10\3\1\0\14\3"+
    "\1\0\1\3\2\377\4\3\1\0\1\3\37\0\1\u0100"+
    "\47\0\1\3\1\u0101\4\0\10\3\1\0\14\3\1\0"+
    "\7\u0101\1\0\1\u0101\21\0\1\3\1\u0102\4\0\10\3"+
    "\1\0\14\3\1\0\3\3\4\u0102\1\0\1\u0102\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[11178];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\43\1\6\11\1\1\3\0\25\1\1\11"+
    "\1\1\1\0\2\1\12\11\7\0\30\1\3\0\21\1"+
    "\1\11\11\1\1\11\3\0\23\1\3\0\20\1\1\0"+
    "\1\1\1\11\1\1\1\11\6\1\1\0\12\1\1\0"+
    "\5\1\1\0\1\1\1\0\4\1\3\0\1\11\1\0"+
    "\1\11\2\1\2\0\3\1\2\0\4\1\1\0\3\1"+
    "\2\0\2\1\2\0\1\11\1\1\1\11\1\0\1\1"+
    "\1\11\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[258];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }
    private Symbol symbol(int type){
        return new Symbol(type, yyline, yycolumn);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexerCup(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  LexerCup(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 42: 
          { return new Symbol(sym.Para, yychar, yyline, yytext());
          }
        case 69: break;
        case 56: 
          { return new Symbol(sym.Imprimir, yychar, yyline, yytext());
          }
        case 70: break;
        case 18: 
          { return new Symbol(sym.Llave_a, yychar, yyline, yytext());
          }
        case 71: break;
        case 23: 
          { return new Symbol(sym.Cadena, yychar, yyline, yytext());
          }
        case 72: break;
        case 39: 
          { return new Symbol(sym.Tcurp, yychar, yyline, yytext());
          }
        case 73: break;
        case 29: 
          { return new Symbol(sym.Op_atribucion_multiplicacion, yychar, yyline, yytext());
          }
        case 74: break;
        case 11: 
          { return new Symbol(sym.Op_bitwise_and, yychar, yyline, yytext());
          }
        case 75: break;
        case 37: 
          { return new Symbol(sym.Hora, yychar, yyline, yytext());
          }
        case 76: break;
        case 12: 
          { return new Symbol(sym.Op_bitwise_or, yychar, yyline, yytext());
          }
        case 77: break;
        case 20: 
          { return new Symbol(sym.Corchete_a, yychar, yyline, yytext());
          }
        case 78: break;
        case 14: 
          { return new Symbol(sym.MayorQue, yychar, yyline, yytext());
          }
        case 79: break;
        case 7: 
          { return new Symbol(sym.Division, yychar, yyline, yytext());
          }
        case 80: break;
        case 53: 
          { return new Symbol(sym.Funcion, yychar, yyline, yytext());
          }
        case 81: break;
        case 48: 
          { return new Symbol(sym.TLogico, yychar, yyline, yytext());
          }
        case 82: break;
        case 34: 
          { return new Symbol(sym.MenorIgual, yychar, yyline, yytext());
          }
        case 83: break;
        case 24: 
          { return new Symbol(sym.Si, yychar, yyline, yytext());
          }
        case 84: break;
        case 66: 
          { return new Symbol(sym.Procedimientos, yychar, yyline, yytext());
          }
        case 85: break;
        case 41: 
          { return new Symbol(sym.Thora, yychar, yyline, yytext());
          }
        case 86: break;
        case 28: 
          { return new Symbol(sym.Op_atribucion_suma, yychar, yyline, yytext());
          }
        case 87: break;
        case 5: 
          { return new Symbol(sym.Comillas, yychar, yyline, yytext());
          }
        case 88: break;
        case 46: 
          { return new Symbol(sym.Hacer, yychar, yyline, yytext());
          }
        case 89: break;
        case 16: 
          { return new Symbol(sym.Parentesis_a, yychar, yyline, yytext());
          }
        case 90: break;
        case 6: 
          { return new Symbol(sym.Resta, yychar, yyline, yytext());
          }
        case 91: break;
        case 58: 
          { return new Symbol(sym.Devolver, yychar, yyline, yytext());
          }
        case 92: break;
        case 40: 
          { return new Symbol(sym.Fin, yychar, yyline, yytext());
          }
        case 93: break;
        case 63: 
          { return new Symbol(sym.Fecha_hora, yychar, yyline, yytext());
          }
        case 94: break;
        case 31: 
          { return new Symbol(sym.Op_logico_or, yychar, yyline, yytext());
          }
        case 95: break;
        case 19: 
          { return new Symbol(sym.Llave_c, yychar, yyline, yytext());
          }
        case 96: break;
        case 45: 
          { return new Symbol(sym.Hasta, yychar, yyline, yytext());
          }
        case 97: break;
        case 65: 
          { return new Symbol(sym.Rfc, yychar, yyline, yytext());
          }
        case 98: break;
        case 36: 
          { return new Symbol(sym.Trfc, yychar, yyline, yytext());
          }
        case 99: break;
        case 21: 
          { return new Symbol(sym.Corchete_c, yychar, yyline, yytext());
          }
        case 100: break;
        case 35: 
          { return new Symbol(sym.Op_atribucion_modulo, yychar, yyline, yytext());
          }
        case 101: break;
        case 44: 
          { return new Symbol(sym.Tfecha, yychar, yyline, yytext());
          }
        case 102: break;
        case 59: 
          { return new Symbol(sym.Mientras, yychar, yyline, yytext());
          }
        case 103: break;
        case 55: 
          { return new Symbol(sym.Variable, yychar, yyline, yytext());
          }
        case 104: break;
        case 13: 
          { return new Symbol(sym.Op_logico_not, yychar, yyline, yytext());
          }
        case 105: break;
        case 17: 
          { return new Symbol(sym.Parentesis_c, yychar, yyline, yytext());
          }
        case 106: break;
        case 50: 
          { return new Symbol(sym.Inicio, yychar, yyline, yytext());
          }
        case 107: break;
        case 33: 
          { return new Symbol(sym.MayorIgual, yychar, yyline, yytext());
          }
        case 108: break;
        case 43: 
          { return new Symbol(sym.Ttexto, yychar, yyline, yytext());
          }
        case 109: break;
        case 22: 
          { return new Symbol(sym.P_coma, yychar, yyline, yytext());
          }
        case 110: break;
        case 62: 
          { return new Symbol(sym.Funciones, yychar, yyline, yytext());
          }
        case 111: break;
        case 57: 
          { return new Symbol(sym.Entonces, yychar, yyline, yytext());
          }
        case 112: break;
        case 15: 
          { return new Symbol(sym.MenorQue, yychar, yyline, yytext());
          }
        case 113: break;
        case 60: 
          { return new Symbol(sym.Tfechahora, yychar, yyline, yytext());
          }
        case 114: break;
        case 10: 
          { return new Symbol(sym.Multiplicacion, yychar, yyline, yytext());
          }
        case 115: break;
        case 52: 
          { return new Symbol(sym.Tdecimal, yychar, yyline, yytext());
          }
        case 116: break;
        case 9: 
          { return new Symbol(sym.Suma, yychar, yyline, yytext());
          }
        case 117: break;
        case 30: 
          { return new Symbol(sym.Op_logico_and, yychar, yyline, yytext());
          }
        case 118: break;
        case 27: 
          { return new Symbol(sym.Igualdad, yychar, yyline, yytext());
          }
        case 119: break;
        case 26: 
          { return new Symbol(sym.Op_atribucion_division, yychar, yyline, yytext());
          }
        case 120: break;
        case 54: 
          { return new Symbol(sym.Fecha, yychar, yyline, yytext());
          }
        case 121: break;
        case 67: 
          { return new Symbol(sym.CodigoPrincipal, yychar, yyline, yytext());
          }
        case 122: break;
        case 51: 
          { return new Symbol(sym.Tsimbolo, yychar, yyline, yytext());
          }
        case 123: break;
        case 1: 
          { return new Symbol(sym.ERROR, yychar, yyline, yytext());
          }
        case 124: break;
        case 32: 
          { return new Symbol(sym.Diferente, yychar, yyline, yytext());
          }
        case 125: break;
        case 47: 
          { return new Symbol(sym.Romper, yychar, yyline, yytext());
          }
        case 126: break;
        case 68: 
          { return new Symbol(sym.Curp, yychar, yyline, yytext());
          }
        case 127: break;
        case 4: 
          { /*Ignore*/
          }
        case 128: break;
        case 8: 
          { return new Symbol(sym.Igual, yychar, yyline, yytext());
          }
        case 129: break;
        case 25: 
          { return new Symbol(sym.Op_atribucion_resta, yychar, yyline, yytext());
          }
        case 130: break;
        case 64: 
          { return new Symbol(sym.Procedimiento, yychar, yyline, yytext());
          }
        case 131: break;
        case 61: 
          { return new Symbol(sym.Variables, yychar, yyline, yytext());
          }
        case 132: break;
        case 2: 
          { return new Symbol(sym.Identificador, yychar, yyline, yytext());
          }
        case 133: break;
        case 3: 
          { return new Symbol(sym.Numero, yychar, yyline, yytext());
          }
        case 134: break;
        case 49: 
          { return new Symbol(sym.Tentero, yychar, yyline, yytext());
          }
        case 135: break;
        case 38: 
          { return new Symbol(sym.Sino, yychar, yyline, yytext());
          }
        case 136: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
