
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 28 22:44:36 PDT 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Llave_c = 62;
  public static final int Llave_a = 61;
  public static final int Ttexto = 7;
  public static final int Diferente = 49;
  public static final int Rfc = 22;
  public static final int Procedimientos = 18;
  public static final int Tsimbolo = 6;
  public static final int Op_atribucion_suma = 53;
  public static final int Variable = 15;
  public static final int Funciones = 17;
  public static final int Fecha_hora = 32;
  public static final int Corchete_c = 64;
  public static final int Corchete_a = 63;
  public static final int Para = 29;
  public static final int Op_logico_or = 42;
  public static final int Op_bitwise_or = 45;
  public static final int Division = 40;
  public static final int Cadena = 66;
  public static final int Parentesis_c = 60;
  public static final int Op_bitwise_and = 44;
  public static final int Parentesis_a = 59;
  public static final int Fin = 25;
  public static final int Hora = 34;
  public static final int Tfecha = 10;
  public static final int P_coma = 65;
  public static final int Hacer = 52;
  public static final int EOF = 0;
  public static final int MayorQue = 46;
  public static final int error = 1;
  public static final int Tdecimal = 5;
  public static final int Funcion = 19;
  public static final int Op_atribucion_modulo = 58;
  public static final int Romper = 31;
  public static final int Curp = 21;
  public static final int Linea = 2;
  public static final int Imprimir = 35;
  public static final int Devolver = 20;
  public static final int Thora = 11;
  public static final int ERROR = 69;
  public static final int Op_atribucion_resta = 54;
  public static final int TLogico = 8;
  public static final int MenorIgual = 51;
  public static final int Entonces = 27;
  public static final int Variables = 14;
  public static final int Op_atribucion_division = 57;
  public static final int Tcurp = 13;
  public static final int Op_logico_not = 43;
  public static final int Op_logico_and = 41;
  public static final int Tfechahora = 9;
  public static final int Inicio = 24;
  public static final int Identificador = 67;
  public static final int Op_atribucion_multiplicacion = 55;
  public static final int Tentero = 4;
  public static final int Si = 26;
  public static final int Resta = 38;
  public static final int MenorQue = 47;
  public static final int MayorIgual = 50;
  public static final int Sino = 28;
  public static final int Igualdad = 48;
  public static final int Mientras = 30;
  public static final int Procedimiento = 23;
  public static final int Fecha = 33;
  public static final int Multiplicacion = 39;
  public static final int Numero = 68;
  public static final int Hasta = 56;
  public static final int Suma = 37;
  public static final int CodigoPrincipal = 16;
  public static final int Trfc = 12;
  public static final int Igual = 36;
  public static final int Comillas = 3;
}

